name = "Swalbe"
uuid = "1073fb09-a5e2-4e80-8bde-f3562efda53f"
authors = ["Zitzeronion <physiknerd@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
